spring.application.name=restaurantportal
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
logging.level.org.springframework=INFO
logging.level.com.capstone=DEBUG
jwt.secret=mySuperSecureKeyThatIsVeryLong1234567890
jwt.expiration=86400000

